### ISSUE TITLE
bug: Update docs in Windows do not work correctly

### ISSUE THREAD

**Issue by tsuyoshicho** [wlemuel/vim-tldr#6]
URL : https://github.com/tldr-pages/tldr/archive/master.zip

above zip  (redirected) file name are `tldr-master.zip` and contains direcotry `tldr-master`
 Run TldrUpdateDocs with default settings, extract to `~/.cach/tldr-master/`.
Then move operation failsed? erase it.

Now, update method include `tldr` command (`tldr -u`).
What about simplification?

**Comment by wlemuel** [comment]
> Then move operation failsed? erase it.  

In the last step, the command is `mv ~/.cache/tldr-master ~/.cache/tldr`,  so the directory of `~/.cache/tldr` will be replaced by the latest data. Can you provide more details about the failing of move operation. Because it works in my computer.

> Now, update method include tldr command (tldr -u).  

This project does not depend on `tldr` command, I will take a look at the implementation of `tldr -u` to optimize this project.

Thank you for your feedback!

**Comment by tsuyoshicho** [comment]
Thankyou for the explanation.
I understand process steps and dependency that it doesn't specifically depend on tldr.

I double-checked the details of the problem.
Sorry for the lack of details.

Env: Windows 11 Pro / Vim 9.0.0814

Reproduce steps:
1. Remove cache (`~/.cache/tldr`)
2. Run `:TldrUpdateDocs`.
    1. First command prompt: Extract tldr-master.zip and create `~/.cach/tldr-master/`.
    2. Second command prompt: process run(done quickly)
    3. Third command prompt: process run(done quickly) 
3. Do not exists cache (`~/.cache/tldr`) and extracted folder(`~/.cach/tldr-master/` ).

`:Tldr` do not work in this state.

I was able to confirm that the folder(`~/.cach/tldr-master/` ) exists during 2.1 process.
I guess 2.2 or 2.3 is rename process?

Last state is wrong, in this problem.

---

Recovery in my environment.
```
$ tldr -u
```

**Comment by wlemuel** [comment]
Thank you for the detailed report.

I have changed the update_doc function to fit the windows environment and pushed a commit to the `develop` branch. But I don't have a windows machine on hand. Could you be kind to help to test the latest [changes](https://github.com/wlemuel/vim-tldr/commit/3252235b181f500ac18d5dc2603aa15a40895208)?

for *unix
```
curl -fLo ~/.cache/tldr-source.zip --create-dirs https://github.com/tldr-pages/tldr/archive/master.zip
unzip -o -d ~/.cache ~/.cache/tldr-source.zip
rm -rf ~/.cache/tldr-source.zip
mv ~/.cache/tldr-master ~/.cache/tldr
```

Equivalent to Windows
```
powershell -c "Invoke-WebRequest -Uri 'https://github.com/tldr-pages/tldr/archive/master.zip' -OutFile '~/.cache/tldr-source.zip'"
powershell -c "Expand-Archive -Path '~/.cache/tldr-source.zip' -DestinationPath '~/.cache/'"
rmdir /Q /S "~/.cache/tldr-source.zip"
move /Y ~/.cache/tldr-master ~/.cache/tldr
```

**Comment by tsuyoshicho** [comment]
@wlemuel san

Thank you for your support and code changes.

Okay I will to try "develop" branch.
But now, above command list/changes seems mistakes.

I tried manually operate above command, "rmdir" work not fine.

Windows cmd's "file deletion command" names are "del" 
It need to change "del /S /F <target>"
`/S` is silent.
`/F` is force.

regards.

**Comment by wlemuel** [comment]
Hi, Thank you for pointing out the mistakes.

I have changed the command to `del` and pushed them to the `develop` branch.
Waiting for the further feedback.

Best regards.

**Comment by tsuyoshicho** [comment]
I tried develop branch

`:TldrUpdateDocs` error happen.

join command failed?

```text
[Tldr] start to download tldr zip
function dein#autoload#_on_cmd[17]..function dein#autoload#_on_cmd[13]..tldr#update_docs の処理中にエラーが検出されました:
行   13:
E15: Invalid expression: "\' -OutFile \'' . expand(g:tldr_saved_zip_path) . '\'"'"
````

**Comment by tsuyoshicho** [comment]
PRed to develop branch

https://github.com/wlemuel/vim-tldr/pull/7

work fine `:TldrUpdateDocs` are checked.

**Comment by wlemuel** [comment]
Thank you for your help.

I have merged the changes to `master` branch.
Have fun with vim-tldr~

regards.

**Comment by tsuyoshicho** [comment]
master branch work fine!

Thanks for your support.

Close this issue.
